name: My gpt
run-name: ${{ github.actor }} is acting!
on: 
# 推送触发
  push:
  # 限制分支
    branches:
      - main
# 推送请求触发
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 把仓库内容复制到虚拟机内
      - name: Checkout repository 
        uses: actions/checkout@v2
      # vite打包
      - name: Build the project
        run: |
          npm install
          npm run build
      #配置ssh环境
      - name: Set Up SSH 
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 121.40.249.233 >> ~/.ssh/known_hosts
      # 将构建产物通过 SSH 上传到服务器
      - name: Upload build artifacts to server
        run: |
          # 将构建产物dist目录通过scp上传到远程服务器上的目录
          scp -r ./dist root@121.40.249.233:/var/www/gpt
      # 在远程服务器上执行脚本构建
      # - name: Deploy to Server
      #   run: |
      #     ssh -i ~/.ssh/id_rsa root@121.40.249.233 'bash -s' < scripts/deploy.sh
